### ISSUE TITLE
Private tabs all get the same ID.

### ISSUE THREAD

**Issue by thruflo** [KyleAMathews/browser-tab-id#2]
One of the things I stumbled across when doing https://github.com/electric-sql/electric/blob/main/clients/typescript/src/util/tab.ts was that localStorage doesn't work in private browsing. (In fact, I found private windows would pretend to support the storage API but would then fail when you tried to use it).

With a UUID implementation, this doesn't matter too much because (assuming your code doesn't error) each private tab gets a new UUID. However, with this lowest-integer implementation, it means each tab in a private browsing session (or any session without localStorage) will get the ID `1`.

I tested this with code like this:

```js
import { TabIdCoordinator } from 'browser-tab-id'

const coordinator = new TabIdCoordinator()
const title = `Tab ID: ${coordinator.tabId}`

document.title = title
document.body.innerText = title
```

Built with `esbuild index.js --bundle --outfile=dist/index.js --servedir=dist` with a `dist/index.html` of:

```html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
  </body>
  <script src="index.js">
  </script>
</html>
```

Verified that in a normal browser window it works:

<img width="686" alt="image" src="https://github.com/KyleAMathews/browser-tab-id/assets/60015/662370cb-7203-4d2b-b548-22f31f99997f">

But in a private browser window all tabs are ID `1`:

<img width="686" alt="image" src="https://github.com/KyleAMathews/browser-tab-id/assets/60015/a43f3d8b-ce77-4d58-a59e-92115cb6d4a5">

**Comment by KyleAMathews** [comment]
That's fine though as I believe they also don't share anything else e.g. indexeddb, etc. The goal is just to coordinate around shared resources and as private tabs don't share anything, they can all have the same id.

**Comment by thruflo** [comment]
Right, yup, that makes sense 👍

**Comment by KyleAMathews** [comment]
👍
